config/routes.rb
Rails.application.routes.draw do

  # root route

  root 'demo#index'

  get 'demo/index'

  get 'demo/about'

  get 'demo/contact'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  # default route
  get ':controller(/:action(/:id))'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false

  def index
    @array = [1, 2, 2, 3, 4, 5]
    @id = params['id']
    @page = params['page']
  end

  def about
    render('about_us')
  end

  def contact
    if ['us', 'ca'].include?(params[:country])
      @phone = '(800) 555-6789'
    elsif params[:country] == 'uk'
      @phone = '(020) 7946 1234'
    else
      @phone = '+1 (987) 654-3210'
    end
    render('contact_us')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.order('position ASC');
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(pages_params)

    if @page.save
      redirect_to(pages_path)
    else
      render(:new)
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(pages_params)
      redirect_to(page_path(@page))
    else
      render(:edit)
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])

    @page.destroy

    redirect_to(pages_path)
  end

  private

  def pages_params
    params.require(:page).permit(:name, :position, :permalink, :visible, :context, :subject_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def show
    # redirect_to(controller: 'demo', action: 'index')
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    # instantiate a new object using form parameters
    @subject = Subject.new(subject_params)

    # try and save the subject
    if @subject.save
      # if the save succeeds, redirect to the index action
      redirect_to(subjects_path)
    else
      # if save fails, redisplay the form to user.
      render(:new)
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to(subject_path(@subject))
    else
      render(:edit)
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])

    @subject.destroy

    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :visiblle, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => { :object => object })
  end
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved.</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/demo/about_us.html.erb
<<h1>About Us</h1>

<%= link_to('Contact Us', { action: 'contact', country: 'us' }) %>

app/views/demo/contact_us.html.erb
<h1>Contact Us</h1>

<p>Contact us on: <%= @phone %></p>

<%= link_to("About Us", { action: 'contact' }) %>

app/views/demo/index.html.erb
<h1>Hello World!</h1>

<% @array.each do |item| %>
  <p><%= item %>
<% end %>

<a href="/students/welldone">Welldone Page</a>

<p><%= link_to("Welldone 2", { controller: 'students', action: 'welldone' })%></p>
<p><%= link_to("Welldone With params", { controller: 'students', action: 'welldone', page: 2, id: 12 })%></p>

<p><%= link_to('All Subjects', subjects_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(form.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Subject ID</th>
    <td><%= form.text_field(:subject_id) %></td>
  </tr>

  <tr>
    <th>Name</th>
    <td><%= form.text_field(:name) %></td>
  </tr>

  <tr>
    <th>Position</th>
    <td><%= form.text_field(:position) %></td>
  </tr>

  <tr>
    <th>Permalink</th>
    <td><%= form.text_field(:permalink) %></td>
  </tr>

  <tr>
    <th>Visible</th>
    <td><%= form.text_field(:visible) %></td>
  </tr>

  <tr>
    <th>Content</th>
    <td><%= form.text_area(:context, size: '50x10') %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<p>
  <%= link_to("<< Back to List", pages_path, :class => "back-link")%>
</p>

<div class="pages new">
  <h2>Delete Page</h2>
  <%= form_for(@page,:method => "delete") do |form| %>
    <p>Are you sure you want to permanently delete this page?</p>

    <p><%= @page.name %></p>
    <div class="form-buttons">
      <%= form.submit("Delete Page") %>
    </div>
  <% end %>
</div>

app/views/pages/edit.html.erb
<p>
  <%= link_to("<< Back to List", pages_path, :class => "back-link")%>
</p>

<div class="pages new">
  <h2>Update Page</h2>
  <%= form_for(@page) do |form| %>
    <%= render(:partial => 'form', :locals => { :form => form }) %>
    <div class="form-buttons">
      <%= form.submit("Update Page") %>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="subjects index">
  <h2>Pages</h2>

  <p><%= link_to("Add New Page", new_page_path, :class => 'action new') %></p>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>Subject</th>
      <th>Position</th>
      <th>Page</th>
      <th>Visible</th>
      <th>Permalink</th>
    </tr>

    <% @pages.each do |page| %>
       <tr>
         <td><%= page.subject.name %></td>
         <td><%= page.position %></td>
         <td><%= page.name %></td>
         <td class="center"><%= page.visible ? 'Yes' : 'No' %></td>
         <td class="center"><%= page.permalink %></td>
         <td class="actions">
            <%= link_to("Show", page_path(page), :class => 'actions show') %>
            <%= link_to("Edit", edit_page_path(page), :class => 'actions edit') %>
            <%= link_to("Delete", delete_page_path(page), :class => 'actions delete') %>
         </td>
       </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<p>
  <%= link_to("<< Back to List", pages_path, :class => "back-link")%>
</p>

<div class="pages new">
  <h2>Create Page</h2>
  <%= form_for(@page, :url => pages_path, :method => "post") do |form| %>
    <%= render(:partial => 'form', :locals => { :form => form }) %>
    <div class="form-buttons">
      <%= form.submit("Create Page") %>
    </div>
  <% end %>
</div>

app/views/pages/show.html.erb
<p>
  <%= link_to('<< Back to List', pages_path, :class => 'back-link') %>
</p>

<div class="pages show">
  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>

    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>

    <tr>
      <th>Visible</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>

    <tr>
      <th>Content</th>
      <td><%= @page.context %></td>
    </tr>

    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>

app/views/students/index.html.erb
<h1>Students</h1>

app/views/students/welldone.html.erb
<h1>Welldone Soldier</h1>

<%= 1 + 1 %>

<br>

<% target ="hello" %>

<%= "Hello #{target}!" %><br>

Page: <%= @page %><br />

Page_Two: <%= params[:page] %><br>

ID: <%= @id %><br>

ID: <%= params[:id] %>

<%= link_to("Back", { controller: 'demo', action: 'index' })%>

app/views/subjects/_form.html.erb
<%= error_messages_for(form.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= form.text_field(:name) %></td>
  </tr>

  <tr>
    <th>Position</th>
    <td><%= form.text_field(:position) %></td>
  </tr>

  <tr>
    <th>Visible</th>
    <td><%= form.text_field(:visiblle) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<p>
  <%= link_to("<< Back to List", subjects_path, :class => "back-link")%>
</p>

<div class="subjects new">
  <h2>Delete Subject</h2>
  <%= form_for(@subject,:method => "delete") do |form| %>
    <p>Are you sure you want to permanently delete this subject?</p>

    <p><%= @subject.name %></p>
    <div class="form-buttons">
      <%= form.submit("Delete Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/edit.html.erb
<p>
  <%= link_to("<< Back to List", subjects_path, :class => "back-link")%>
</p>

<div class="subjects new">
  <h2>Update Subject</h2>
  <%= form_for(@subject) do |form| %>
    <%= render(:partial => 'form', :locals => { :form => form }) %>
    <div class="form-buttons">
      <%= form.submit("Update Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/index.html.erb
<div class="subjects index">
  <h2>Subjects</h2>

  <p><%= link_to("Add New Subject", new_subject_path, :class => 'action new') %></p>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>

    <% @subjects.each do |subject| %>
       <tr>
         <td><%= subject.position %></td>
         <td><%= subject.name %></td>
         <td class="center"><%= subject.visiblle ? 'Yes' : 'No' %></td>
         <td class="center"><%= subject.pages.size %></td>
         <td class="actions">
            <%= link_to("Show", subject_path(subject), :class => 'actions show') %>
            <%= link_to("Edit", edit_subject_path(subject), :class => 'actions edit') %>
            <%= link_to("Delete", delete_subject_path(subject), :class => 'actions delete') %>
         </td>
       </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<p>
  <%= link_to("<< Back to List", subjects_path, :class => "back-link")%>
</p>

<div class="subjects new">
  <h2>Create Subject</h2>
  <%= form_for(@subject, :url => subjects_path, :method => "post") do |form| %>
    <%= render(:partial => 'form', :locals => { :form => form }) %>
    <div class="form-buttons">
      <%= form.submit("Create Subject") %>
    </div>
  <% end %>
</div>

app/views/subjects/show.html.erb
<p>
  <%= link_to('<< Back to List', subjects_path, :class => 'back-link') %>
</p>

<div class="subjects show">
  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>

    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>

    <tr>
      <th>Visible</th>
      <td><%= @subject.visiblle ? 'true' : 'false' %></td>
    </tr>

    <tr>
      <th>Created</th>
      <td><%= @subject.created_at %></td>
    </tr>

    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at %></td>
    </tr>
  </table>
</div>